server:
  port: 9000

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        # Route 1: Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            # 2. Add Rate Limiting Filter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # Allow 10 requests per second
                redis-rate-limiter.burstCapacity: 20  # Allow short bursts of 20
                redis-rate-limiter.requestedTokens: 1 # Each request costs 1 token

        # Route 2: Order Service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        # Route 3: Inventory Service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/shopwise-realm

