spring.application.name=order-service
server.port=8081

# Database Configuration (Localhost via Port 3307)
spring.datasource.url=jdbc:mysql://localhost:3307/order_service
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info,prometheus

# Resilience4j Configuration
# If 50% of requests fail, open the circuit
resilience4j.circuitbreaker.instances.inventory.failure-rate-threshold=50
# Wait 5 seconds in "Open" state before trying again
resilience4j.circuitbreaker.instances.inventory.wait-duration-in-open-state=5s
# Allow 3 requests in "Half-Open" state to check if service is back
resilience4j.circuitbreaker.instances.inventory.permitted-number-of-calls-in-half-open-state=3
# Use a sliding window of the last 5 calls to calculate failure rate
resilience4j.circuitbreaker.instances.inventory.sliding-window-size=5

# TIMEOUT CONFIG (Crucial Fix) - Increase to 5s or 10s
resilience4j.timelimiter.instances.inventory.timeout-duration=5s

# Enable Prometheus Metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Sampling Probability (1.0 = 100% of requests)
management.tracing.sampling.probability=1.0
# Send traces to Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=notificationTopic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer






