spring.application.name=discovery-server
server.port=8761

# I am the server, so I don't need to register with myself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Send 100% of requests to Zipkin
management.tracing.sampling.probability=1.0