spring.application.name=product-service
spring.data.mongodb.uri=mongodb+srv://EComMicroProject:EComMicroProject@cluster0.9jkt278.mongodb.net/product-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# Sampling Probability (1.0 = 100% of requests)
management.tracing.sampling.probability=1.0
# Send traces to Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans