spring.application.name=inventory-service
server.port=8083

# Database (We will use the same MySQL server but a new Schema)
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
